name: CheckIP
description: Checks a players IP!
version: 2.0
main: CheckIP\Main
author: OpenBuild Dev Team (Pogogo007)
api: 2.0.0
commands:
 checkip:
  description: command to check a players IP!
