name: CheckIP
description: Checks a players IP!
version: "1.1_beta"
main: CheckIP\Main
author: OpenBuild Dev Team (Pogogo007 SavionLegendZzz)
api: 1.13.0
commands:
 checkip:
  description: command to check a players IP!
  permission: check.ip.perm
